syntax = "proto3";
import "google/protobuf/empty.proto";
import "array.proto";


service AsynchronousADMMSolver {
    rpc SetInitialFeasibleSolution(stream Chunk) returns (google.protobuf.Empty) {}
    rpc SetNullSpaceBasis(stream Chunk) returns (google.protobuf.Empty) {}
    rpc RequestChunk(google.protobuf.Empty) returns (stream Chunk) {}
    rpc QueryState(google.protobuf.Empty) returns (State) {}
    rpc SetSolverParameters(SolverParameters) returns (google.protobuf.Empty) {}
    rpc SetActiveCommodityCount(ActiveCommodityCount) returns (google.protobuf.Empty) {}
    rpc Close(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message ControllerMessage {
    SerializedNumpyArrayMessage P_bar_t = 1;
    SerializedNumpyArrayMessage u_t = 2;
    SerializedNumpyArrayMessage Y_bar_t = 3;
}

message SwitchMessage {
    int32 worker_id = 1;
    int32 runtime_ns = 2;
    SerializedNumpyArrayMessage means = 3;
}

message State {
    bool ready = 1;
}

message SolverParameters {
    int32 NumberOfEpochs = 1;
    int32 NumberOfNetworkUpdates = 2;
    int32 NumberOfLocalUpdates = 3;
    float Rho = 4;
    float Eta = 5;
    float Gamma = 6;
    float Kappa = 7;
    int32 QPIterations = 8;
    string QPMethod = 9;
    int32 NumWorkers = 10;
    string Precision = 11;
    float BigGamma = 12;
    int32 Seed = 13;
    int32 Upsilon = 14;
    int32 Sigma = 15;
    int32 WorkerBatchSize = 16;
    float ADMMConvTol = 17;
}

message ActiveCommodityCount {
    int32 TotalNumberOfCommodities = 1;
}
