syntax = "proto3";
import "google/protobuf/empty.proto";
import "array.proto";


service DistributedADMMSolver {
    rpc SetInitialFeasibleSolution(stream Chunk) returns (google.protobuf.Empty) {}
    rpc SetNullSpaceBasis(stream Chunk) returns (google.protobuf.Empty) {}
    rpc SetCommodityInOutMask(stream Chunk) returns (google.protobuf.Empty) {}
    rpc DoNetworkUpdate(NetworkUpdateRequest) returns (NetworkUpdateResponse) {}
    rpc ResetInnerDualVariable(google.protobuf.Empty) returns (google.protobuf.Empty) {}
    rpc UpdateWorkerNode(UpdateMessage) returns (google.protobuf.Empty) {}
    rpc UpdateMaxFlowWorkerNode(UpdateMessage) returns (google.protobuf.Empty) {}
    rpc RequestChunk(google.protobuf.Empty) returns (stream Chunk) {}
    rpc RequestAggregate(google.protobuf.Empty) returns (SerializedNumpyArrayMessage) {}
    rpc QueryState(google.protobuf.Empty) returns (State) {}
    rpc SetSolverParameters(SolverParameters) returns (google.protobuf.Empty) {}
    rpc SetActiveCommodityCount(ActiveCommodityCount) returns (google.protobuf.Empty) {}
    rpc Close(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message UpdateMessage {
    SerializedNumpyArrayMessage sharing_bias = 1;
    int32 xid = 2;
}

message MaxFlowUpdateMessage {
    SerializedNumpyArrayMessage J_bar_e = 1;
    SerializedNumpyArrayMessage f_e = 2;
    SerializedNumpyArrayMessage X_bar_e = 3;
    SerializedNumpyArrayMessage TAU_e = 4;
    int32 xid = 5;
}

message NetworkUpdateRequest {
    int32 epoch = 1;
    int32 xid = 2;
}

message NetworkUpdateResponse {
    int32 worker_id = 1;
    int32 runtime_ns = 2;
    SerializedNumpyArrayMessage means = 3;
    int32 xid = 4;
}

message State {
    bool ready = 1;
}

message SolverParameters {
    optional int32 OuterLoopRounds = 1;
    optional int32 InnerLoopRounds = 2;
    optional float Rho = 3;
    optional float Eta = 4;
    optional float Gamma = 5;
    optional float Beta = 6;
    optional bool UseSparseBasis = 7;
    optional int32 SwitchIterations = 8;
    optional float ConvTol = 9;
    optional string Precision = 10;
    optional int32 TMSeed = 11;
    optional int32 NumWorkers = 12;
}

message ActiveCommodityCount {
    int32 TotalNumberOfCommodities = 1;
}
