syntax = "proto3";
import "google/protobuf/empty.proto";
import "array.proto";
import "graph.proto";


service DistributedADMMSolver {
    rpc SetTopology(Topology) returns (google.protobuf.Empty) {}
    rpc DoNetworkUpdate(NetworkUpdateRequest) returns (NetworkUpdateResponse) {}
    rpc UpdateWorkerNode(UpdateMessage) returns (google.protobuf.Empty) {}
    rpc SetDemands(SerializedNumpyArrayMessage) returns (SerializedNumpyArrayMessage) {}
    rpc RequestChunk(google.protobuf.Empty) returns (stream Chunk) {}
    rpc RequestAggregate(google.protobuf.Empty) returns (SerializedNumpyArrayMessage) {}
    rpc QueryState(google.protobuf.Empty) returns (State) {}
    rpc SetSolverParameters(SolverParameters) returns (google.protobuf.Empty) {}
    rpc Close(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message UpdateMessage {
    SerializedNumpyArrayMessage sharing_bias = 1;
    int32 xid = 2;
}

message NetworkUpdateRequest {
    int32 epoch = 1;
    int32 xid = 2;
}

message NetworkUpdateResponse {
    int32 worker_id = 1;
    int32 runtime_ns = 2;
    SerializedNumpyArrayMessage means = 3;
    int32 xid = 4;
}

message State {
    bool ready = 1;
}

message SolverParameters {
    optional int32 OuterLoopRounds = 1;
    optional int32 InnerLoopRounds = 2;
    optional float Rho = 3;
    optional float Eta = 4;
    optional float Gamma = 5;
    optional float Beta = 6;
    optional int32 SwitchIterations = 7;
    optional string Precision = 8;
    optional bool ScaleWithCapacity = 9;
    optional int32 NumWorkers = 10;
}
