syntax = "proto3";
import "google/protobuf/empty.proto";
import "array.proto";


service DistributedADMMSolver {
    rpc SetAlphaShape(ArrayShape) returns (google.protobuf.Empty) {}
    rpc SetAlphaRows(stream SerializedNumpyArrayMessage) returns (google.protobuf.Empty) {}
    rpc SetAlphaCols(stream SerializedNumpyArrayMessage) returns (google.protobuf.Empty) {}
    rpc SetBeta(stream Chunk) returns (google.protobuf.Empty) {}
    rpc SetDemands(stream Chunk) returns (google.protobuf.Empty) {}
    rpc DoNetworkUpdate(NetworkUpdateRequest) returns (NetworkUpdateResponse) {}
    rpc UpdateWorkerNode(UpdateMessage) returns (google.protobuf.Empty) {}
    rpc RequestChunk(google.protobuf.Empty) returns (stream Chunk) {}
    rpc QueryState(google.protobuf.Empty) returns (State) {}
    rpc SetSolverParameters(SolverParameters) returns (google.protobuf.Empty) {}
    rpc SetActiveCommodityCount(ActiveCommodityCount) returns (google.protobuf.Empty) {}
    rpc Close(google.protobuf.Empty) returns (google.protobuf.Empty) {}
    rpc JITWarmStart(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message UpdateMessage {
    SerializedNumpyArrayMessage sharing_bias = 1;
    int32 xid = 2;
}

message NetworkUpdateRequest {
    int32 epoch = 1;
    int32 xid = 2;
}

message NetworkUpdateResponse {
    int32 worker_id = 1;
    int32 runtime_ns = 2;
    SerializedNumpyArrayMessage means = 3;
    int32 xid = 4;
}

message State {
    bool ready = 1;
}

message SolverParameters {
    optional int32 NumberOfPathsPerCommodity = 1;
    optional int32 OuterLoopRounds = 2;
    optional int32 InnerLoopRounds = 3;
    optional float Rho = 4;
    optional float Eta = 5;
    optional float Gamma = 6;
    optional int32 SwitchIterations = 7;
    optional float ConvTol = 8;
    optional string Precision = 9;
    optional int32 TMSeed = 10;
    optional int32 NumWorkers = 11;
}

message ActiveCommodityCount {
    int32 TotalNumberOfCommodities = 1;
}
