---
# Prepare controller/worker nodes from scratch.
- name: Configure APT dependencies
  hosts: controller_group:workers_group
  become: true
  tasks:

  - name: Gather Package Facts
    package_facts:
      manager: apt

  - name: Ensure git
    ansible.builtin.apt:
      update_cache: true
      name: git
    when: '"git" not in ansible_facts.packages'

- name: Clone repo and configure PIP
  hosts: controller_group:workers_group
  remote_user: aghavidel
  tasks:

  - name: Clone repo with force
    ansible.builtin.git:
      repo: https://{{access_token}}@github.com/USC-NSL/DistributedTE.git
      clone: true
      force: true
      dest: /home/aghavidel/DistributedTE

  - name: PIP install requirements
    ansible.builtin.pip:
      requirements: /home/aghavidel/DistributedTE/requirements.txt

- name: Get the zoo
  hosts: controller_group
  remote_user: aghavidel
  tasks:

  - name: Stat the Zoo directory
    ansible.builtin.stat:
      path: /home/aghavidel/DistributedTE/topologies/zoo
    register: zoo_dir
  - name: Download and unzip the Topology Zoo dataset
    command: chdir=/home/aghavidel/DistributedTE python3 -m topologies.get_topology_zoo
    when: (zoo_dir.stat.isdir is not defined or not zoo_dir.stat.isdir)

- name: Prepare gRPC
  hosts: controller_group:workers_group
  remote_user: aghavidel
  tasks:

  - name: Compile protobuffs
    command: chdir=/home/aghavidel/DistributedTE python3 protos/__init__.py

- name: Copy TE Worker Service File
  hosts: workers_group
  become: true
  vars:
    worker_env:
      - key: WORKER_ID
        value: "{{worker_id}}"
  tasks:
    - name: Copy TE Worker Service File To Systemd
      command: chdir=/home/aghavidel/DistributedTE sudo cp ansible/distributed_admm/te_worker.service /etc/systemd/user
    - name: Set WORKER_ID Env-Var
      ansible.builtin.lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_items: "{{ worker_env }}"
    - name: Source ENV
      shell: ". /etc/environment"

- name: Enable TE Worker Service
  hosts: workers_group
  remote_user: aghavidel
  tasks:
    - name: Give EXEC Premission To Launcher
      command: chdir=/home/aghavidel/DistributedTE chmod +x ansible/distributed_admm/launch_worker.sh
    - name: Restart Systemd (User Level)
      command: systemctl --user daemon-reload
