---
# Prepare controller/worker nodes from scratch (i.e. assume no packages are installed)
- name: Configure APT dependencies
  hosts: controller_group:workers_group
  become: true
  tasks:
  - name: Gather Package Facts
    package_facts:
      manager: apt

  - name: Ensure git
    ansible.builtin.apt:
      update_cache: true
      name: git
    when: '"git" not in ansible_facts.packages'
  
  - name: Install python-dev
    ansible.builtin.apt:
      name: python3-dev
      state: present

- name: Clone repo and configure PIP
  hosts: controller_group:workers_group
  gather_facts: false
  remote_user: "{{ lookup('env', 'SPHERE_USER') }}"
  vars: 
    access_token: "{{ lookup('env', 'GIT_ACCESS_TOKEN') }}"
    path_home: "{{ lookup('env', 'SPHERE_HOME') }}"
    path_venv: "{{ lookup('env', 'VENV_HOME') }}"
    branch: "{{ lookup('env', 'GIT_BRANCH') }}"
  
  tasks:
  - name: Clone repo with force
    ansible.builtin.git:
      repo: https://{{access_token}}@github.com/USC-NSL/DistributedTE.git
      clone: true
      force: true
      dest: "{{path_home}}"
      version: "{{branch}}"
  
  - name: Create a Python virtual environment
    ansible.builtin.command:
      cmd: python3 -m venv "{{path_venv}}"
    args:
      creates: "{{path_venv}}/bin/activate"

  - name: PIP install UV
    command: "{{path_venv}}/bin/python -m pip install uv"
  
  - name: UV install requirements
    command: "{{path_venv}}/bin/python -m pip install -r requirements.txt"

  - name: Compile protobuffs
    command: chdir="{{path_home}}" "{{path_venv}}/bin/python protos/__init__.py"

- name: Copy TE Worker Service File
  hosts: workers_group
  gather_facts: false
  become: true
  vars: 
    path_home: "{{ lookup('env', 'SPHERE_HOME') }}"
    path_service: "{{ lookup('env', 'SERVICE_FILE' )}}"
    path_launch: "{{ lookup('env', 'LAUNCH_FILE' )}}"
    worker_env:
      - key: WORKER_ID
        value: "{{worker_id}}"
  module_defaults:
    ansible.builtin.shell:
      chdir: "{{path_home}}"
    ansible.builtin.command:
      chdir: "{{path_home}}"
  tasks:
    - name: Copy TE Worker Service File To Systemd
      command: sudo cp "{{path_service}}" /etc/systemd/user
    
    - name: Set WORKER_ID Env-Var
      ansible.builtin.lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_items: "{{ worker_env }}"
    
    - name: Source ENV
      shell: ". /etc/environment"
    
    - name: Allow Service To Linger
      command: sudo loginctl enable-linger "{{ lookup('env', 'SPHERE_USER') }}"
    
    - name: Give EXEC Premission To Launcher
      command: chmod +x "{{path_launch}}"
    
    - name: Restart Systemd (User Level)
      command: systemctl --user daemon-reload
