---
# Playbook for updating code only
- name: Pull changes
  hosts: controller_group:workers_group
  serial: 100
  gather_facts: false
  remote_user: "{{ lookup('env', 'SPHERE_USER') }}"
  vars: 
    access_token: "{{ lookup('env', 'GIT_ACCESS_TOKEN') }}"
    path_home: "{{ lookup('env', 'SPHERE_HOME') }}"
    path_venv: "{{ lookup('env', 'VENV_HOME') }}"
    path_launch: "{{ lookup('env', 'LAUNCH_FILE' )}}"
    branch: "{{ lookup('env', 'GIT_BRANCH') }}"
  module_defaults:
    ansible.builtin.shell:
      chdir: "{{path_home}}"
    ansible.builtin.command:
      chdir: "{{path_home}}"
  tasks:
  - name: Clone repo with force
    ansible.builtin.git:
      repo: https://{{access_token}}@github.com/USC-NSL/DistributedTE.git
      clone: true
      force: true
      dest: "{{path_home}}"
      version: "{{branch}}"
  
  - name: Compile protobuffs
    ansible.builtin.shell: "{{path_venv}}/bin/python protos/__init__.py"
    args:
      chdir: "{{path_home}}"

  - name: Give EXEC Premission To Launcher
    command: chdir="{{path_home}}" chmod +x ./"{{path_launch}}"
    when: "'workers_group' in group_names"
