---
# Remote `rsync` over all worker nodes to push the current code on the local
- hosts: workers_group
  gather_facts: false
  remote_user: "{{ lookup('env', 'SPHERE_USER') }}"
  vars: 
    path_home: "{{ lookup('env', 'SPHERE_HOME') }}"
    path_venv: "{{ lookup('env', 'VENV_HOME') }}"
    path_launch: "{{ lookup('env', 'LAUNCH_FILE' )}}"
  tasks:
  - name: Sync project respecting .gitignore
    ansible.posix.synchronize:
      src: "{{path_home}}/"
      dest: "{{path_home}}"
      rsync_opts:
        - "--exclude=.git"
        - "--exclude=results"
        # - "--filter=: .gitignore"
  - name: Compile protobuffs
    ansible.builtin.shell: "{{path_venv}}/bin/python protos/__init__.py"
    args:
      chdir: "{{path_home}}"
  - name: Give EXEC Premission To Launcher
    command: chdir="{{path_home}}" chmod +x ./"{{path_launch}}"
    when: "'workers_group' in group_names"
