---
# Spawn workers and a controller node for a distributed test
- name: Set Multicast ENV
  hosts: workers_group
  gather_facts: false
  remote_user: "{{ lookup('env', 'SPHERE_USER') }}"
  vars:
    runtime_env:
      - key: TE_MULTICAST
        value: "{{multicast}}"
  tasks:
    - name: Set TE_MULTICAST Env-Var
      ansible.builtin.lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_items: "{{ runtime_env }}"
      when: 'worker_id|int < upto|int'
    - name: Source ENV
      shell: ". /etc/environment"
      when: 'worker_id|int < upto|int'

- name: Start-Wait-Stop TE Workers
  hosts: workers_group
  remote_user: "{{ lookup('env', 'SPHERE_USER') }}"
  gather_facts: false
  vars:
    upto: "{{num_hosts}}"
  tasks:
    - name: Restart Systemd (User Level)
      command: systemctl --user daemon-reload
      when: 'worker_id|int < upto|int'
    - name: Start Worker Services
      command: systemctl --user start te_worker.service
      when: 'worker_id|int < upto|int'
    - name: Pause for the controller ...
      ansible.builtin.pause:
        prompt: "Bring up the controller. Once done, press <ENTER> to cleanup ..."
        echo: false
    - name: Stop Worker Services
      command: systemctl --user stop te_worker.service
      when: 'worker_id|int < upto|int'

- name: Get Controller Plot
  hosts: controller_group
  remote_user: "{{ lookup('env', 'SPHERE_USER') }}"
  gather_facts: false
  tasks:
    - name: Get `res.png`
      fetch:
        src: /home/aghavidel/DistributedTE/res.png
        dest: /home/aghavidel/res.png
        flat: true
  
