---
# Prepare controller/worker nodes assuming PIP/APT/Zoo dependencies are already satisfied
- name: Prepare gRPC
  hosts: controller_group:workers_group
  gather_facts: false
  remote_user: "{{ lookup('env', 'SPHERE_USER') }}"
  vars: 
    path_home: "{{ lookup('env', 'SPHERE_HOME') }}"
    path_venv: "{{ lookup('env', 'VENV_HOME') }}"
  tasks:
  - name: Compile protobuffs
    command: chdir="{{path_home}}" "{{path_venv}}/bin/python protos/__init__.py"

- name: Copy TE Worker Service File
  hosts: workers_group
  remote_user: "{{ lookup('env', 'SPHERE_USER') }}"
  gather_facts: false
  vars:
    path_home: "{{ lookup('env', 'SPHERE_HOME') }}"
    path_launch: "{{ lookup('env', 'LAUNCH_FILE' )}}"
    path_service: "{{ lookup('env', 'SERVICE_FILE' )}}"
    worker_env:
      - key: WORKER_ID
        value: "{{worker_id}}"
  module_defaults:
    ansible.builtin.shell:
      chdir: "{{path_home}}"
    ansible.builtin.command:
      chdir: "{{path_home}}"
  tasks:
    - name: Copy TE Worker Service File To Systemd
      command: sudo cp "{{path_service}}" /etc/systemd/user
    - name: Set WORKER_ID Env-Var
      ansible.builtin.lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_items: "{{ worker_env }}"
    - name: Source ENV
      shell: ". /etc/environment"
    - name: Allow Service To Linger
      command: sudo loginctl enable-linger aghavidel
    - name: Give EXEC Premission To Launcher
      command: chdir="{{path_home}}" chmod +x "{{path_launch}}"
    - name: Restart Systemd (User Level)
      command: systemctl --user daemon-reload
