from gurobipy import GRB

TM_DIR = "traffic_models/traffic_matrices"

"""When deciding feasibility, if two values are closer than this, we consider them to be the same"""
FLOAT_RES = 1e-6

# GUROBI SPECIFIC
DEFAULT_SOLVER_METHOD = GRB.METHOD_BARRIER
DEFAULT_NUMERIC_FOCUS = 1
DEFAULT_BARRIER_CONVERGENCE_TOLERANCE = 1e-4
DEFAULT_FEASIBILITY_TOLERANCE = 1e-4
DEFAULT_GUROBI_LOG_FILE = ''

# DISTRIBUTED SPECIFIC
DEFAULT_EPSILON_OE = 1
DEFAULT_EPSILON_KE = 1
DEFAULT_ALPHA = 5e-2
DEFAULT_BETA = 5e-2
DEFAULT_SEED = 12345
DEFAULT_NUMBER_OF_NODE_PROCESSES = 5

# ADMM SPECIFIC
DEFAULT_RHO = 1e-3
DEFAULT_ETA = 1e-3
DEFAULT_NUMBER_OF_NETWORK_UPDATES = 10
DEFAULT_MU = 10
DEFAULT_TAU_INC = 2
DEFAULT_TAU_DEC = 2
