from enum import Enum, unique

TM_DIR = "traffic_models/traffic_matrices"

@unique
class SolverMethod(Enum):
    PRIMAL_SIMPLEX = 0
    DUAL_SIMPLEX = 1
    BARRIER = 2
    CONCURRENT = 3
    PRIMAL_AND_DUAL = 5

# GUROBI SPECIFIC
DEFAULT_SOLVER_METHOD = SolverMethod.CONCURRENT
DEFAULT_NUMERIC_FOCUS = 1
DEFAULT_BARRIER_CONVERGENCE_TOLERANCE = 1e-8
DEFAULT_OPTIMALITY_TOLERANCE = 1e-6
DEFAULT_FEASIBILITY_TOLERANCE = 1e-6
DEFAULT_GUROBI_LOG_FILE = ''

# DISTRIBUTED SPECIFIC
DEFAULT_EPSILON_OE = 1
DEFAULT_EPSILON_KE = 1
DEFAULT_ALPHA = 5e-2
DEFAULT_BETA = 5e-2
DEFAULT_SEED = 12345
DEFAULT_NUMBER_OF_NODE_PROCESSES = 5
